apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  labels:
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 27.8.0
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-prometheus-stack
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 70.4.1
      chart: kube-prometheus-stack
      helm:
        valueFiles:
        - $values/grafana/values.yaml
    - repoURL: git@github.com:rmsantis/monitoring.git
      targetRevision: main
      ref: values      
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
