apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crds
  namespace: argocd
spec:
  destination:
    namespace: stack
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 19.0.0
    chart: prometheus-operator-crds
    helm:
      valueFiles:
        - values.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions: 
      - ServerSideApply=true